[package]
name = "tetris_Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck            = "1.25.0"
sysinfo             = "0.39.5"
bit-matrix          = "0.10.0"
bit_field           = "0.10.3"
tokio = { version = "1.52.3", features = ["full"] }

slint ="1.17.0"
[build-dependencies]
slint-build = "1.17.0"