
[package]
name = "search_rust"
version = "0.1.2"
edition = "2018"
[[bin]]
name = "search_rust_app"  # バイナリ名を一意に変更
path = "src/main.rs"
[profile.release]
debug = true

[lib]
name = "search_rust"
crate-type = ["cdylib"]
[features]
portable_simd = []
[dependencies]

windows = { version = "0.61.1", features = [
    "Win32_Foundation", 
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Memory",
    "Win32_System_Threading"
    ]}

read-process-memory = "0.1.6"
bytemuck            = "1.23.0"
sysinfo             = "0.35.1"
bit-matrix          = "0.8.1"
bit_field           = "0.10.2"
heapless            = "0.8.0"
fxhash              =  "0.2.1"
rayon               = "1.10.0"


pyo3 = { version = "0.25.0", features = ["extension-module"] }
numpy = "0.25.0"

